// nios_system.v

// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module nios_system (
		input  wire        clk_clk,          //        clk.clk
		output wire [7:0]  h0_export,        //         h0.export
		output wire [7:0]  h1_export,        //         h1.export
		output wire [7:0]  h2_export,        //         h2.export
		output wire [7:0]  h3_export,        //         h3.export
		output wire [7:0]  h4_export,        //         h4.export
		output wire [7:0]  h5_export,        //         h5.export
		output wire [7:0]  h6_export,        //         h6.export
		output wire [7:0]  h7_export,        //         h7.export
		inout  wire [7:0]  lcd_DATA,         //        lcd.DATA
		output wire        lcd_ON,           //           .ON
		output wire        lcd_BLON,         //           .BLON
		output wire        lcd_EN,           //           .EN
		output wire        lcd_RS,           //           .RS
		output wire        lcd_RW,           //           .RW
		output wire [7:0]  leds_export,      //       leds.export
		input  wire        reset_reset,      //      reset.reset
		output wire        sdram_clk_clk,    //  sdram_clk.clk
		output wire [12:0] sdram_wire_addr,  // sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,    //           .ba
		output wire        sdram_wire_cas_n, //           .cas_n
		output wire        sdram_wire_cke,   //           .cke
		output wire        sdram_wire_cs_n,  //           .cs_n
		inout  wire [31:0] sdram_wire_dq,    //           .dq
		output wire [3:0]  sdram_wire_dqm,   //           .dqm
		output wire        sdram_wire_ras_n, //           .ras_n
		output wire        sdram_wire_we_n,  //           .we_n
		input  wire [7:0]  switches_export   //   switches.export
	);

	wire         clocks_sys_clk_clk;                                             // clocks:sys_clk_clk -> [H0:clk, H1:clk, H2:clk, H3:clk, H4:clk, H5:clk, H6:clk, H7:clk, LEDs:clk, character_lcd_0:clk, irq_mapper:clk, jtag_uart_0:clk, mm_interconnect_0:clocks_sys_clk_clk, nios2_qsys_0:clk, onchip_memory2_0:clk, rst_controller:clk, sdram:clk, switches:clk]
	wire  [31:0] nios2_qsys_0_data_master_readdata;                              // mm_interconnect_0:nios2_qsys_0_data_master_readdata -> nios2_qsys_0:d_readdata
	wire         nios2_qsys_0_data_master_waitrequest;                           // mm_interconnect_0:nios2_qsys_0_data_master_waitrequest -> nios2_qsys_0:d_waitrequest
	wire         nios2_qsys_0_data_master_debugaccess;                           // nios2_qsys_0:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:nios2_qsys_0_data_master_debugaccess
	wire  [27:0] nios2_qsys_0_data_master_address;                               // nios2_qsys_0:d_address -> mm_interconnect_0:nios2_qsys_0_data_master_address
	wire   [3:0] nios2_qsys_0_data_master_byteenable;                            // nios2_qsys_0:d_byteenable -> mm_interconnect_0:nios2_qsys_0_data_master_byteenable
	wire         nios2_qsys_0_data_master_read;                                  // nios2_qsys_0:d_read -> mm_interconnect_0:nios2_qsys_0_data_master_read
	wire         nios2_qsys_0_data_master_readdatavalid;                         // mm_interconnect_0:nios2_qsys_0_data_master_readdatavalid -> nios2_qsys_0:d_readdatavalid
	wire         nios2_qsys_0_data_master_write;                                 // nios2_qsys_0:d_write -> mm_interconnect_0:nios2_qsys_0_data_master_write
	wire  [31:0] nios2_qsys_0_data_master_writedata;                             // nios2_qsys_0:d_writedata -> mm_interconnect_0:nios2_qsys_0_data_master_writedata
	wire  [31:0] nios2_qsys_0_instruction_master_readdata;                       // mm_interconnect_0:nios2_qsys_0_instruction_master_readdata -> nios2_qsys_0:i_readdata
	wire         nios2_qsys_0_instruction_master_waitrequest;                    // mm_interconnect_0:nios2_qsys_0_instruction_master_waitrequest -> nios2_qsys_0:i_waitrequest
	wire  [27:0] nios2_qsys_0_instruction_master_address;                        // nios2_qsys_0:i_address -> mm_interconnect_0:nios2_qsys_0_instruction_master_address
	wire         nios2_qsys_0_instruction_master_read;                           // nios2_qsys_0:i_read -> mm_interconnect_0:nios2_qsys_0_instruction_master_read
	wire         nios2_qsys_0_instruction_master_readdatavalid;                  // mm_interconnect_0:nios2_qsys_0_instruction_master_readdatavalid -> nios2_qsys_0:i_readdatavalid
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;       // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest;    // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;           // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;          // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;      // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire         mm_interconnect_0_character_lcd_0_avalon_lcd_slave_chipselect;  // mm_interconnect_0:character_lcd_0_avalon_lcd_slave_chipselect -> character_lcd_0:chipselect
	wire   [7:0] mm_interconnect_0_character_lcd_0_avalon_lcd_slave_readdata;    // character_lcd_0:readdata -> mm_interconnect_0:character_lcd_0_avalon_lcd_slave_readdata
	wire         mm_interconnect_0_character_lcd_0_avalon_lcd_slave_waitrequest; // character_lcd_0:waitrequest -> mm_interconnect_0:character_lcd_0_avalon_lcd_slave_waitrequest
	wire   [0:0] mm_interconnect_0_character_lcd_0_avalon_lcd_slave_address;     // mm_interconnect_0:character_lcd_0_avalon_lcd_slave_address -> character_lcd_0:address
	wire         mm_interconnect_0_character_lcd_0_avalon_lcd_slave_read;        // mm_interconnect_0:character_lcd_0_avalon_lcd_slave_read -> character_lcd_0:read
	wire         mm_interconnect_0_character_lcd_0_avalon_lcd_slave_write;       // mm_interconnect_0:character_lcd_0_avalon_lcd_slave_write -> character_lcd_0:write
	wire   [7:0] mm_interconnect_0_character_lcd_0_avalon_lcd_slave_writedata;   // mm_interconnect_0:character_lcd_0_avalon_lcd_slave_writedata -> character_lcd_0:writedata
	wire  [31:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_readdata;      // nios2_qsys_0:jtag_debug_module_readdata -> mm_interconnect_0:nios2_qsys_0_jtag_debug_module_readdata
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_waitrequest;   // nios2_qsys_0:jtag_debug_module_waitrequest -> mm_interconnect_0:nios2_qsys_0_jtag_debug_module_waitrequest
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_debugaccess;   // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_debugaccess -> nios2_qsys_0:jtag_debug_module_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_address;       // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_address -> nios2_qsys_0:jtag_debug_module_address
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_read;          // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_read -> nios2_qsys_0:jtag_debug_module_read
	wire   [3:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_byteenable;    // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_byteenable -> nios2_qsys_0:jtag_debug_module_byteenable
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_write;         // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_write -> nios2_qsys_0:jtag_debug_module_write
	wire  [31:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_writedata;     // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_writedata -> nios2_qsys_0:jtag_debug_module_writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_chipselect;               // mm_interconnect_0:onchip_memory2_0_s1_chipselect -> onchip_memory2_0:chipselect
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_readdata;                 // onchip_memory2_0:readdata -> mm_interconnect_0:onchip_memory2_0_s1_readdata
	wire   [9:0] mm_interconnect_0_onchip_memory2_0_s1_address;                  // mm_interconnect_0:onchip_memory2_0_s1_address -> onchip_memory2_0:address
	wire   [3:0] mm_interconnect_0_onchip_memory2_0_s1_byteenable;               // mm_interconnect_0:onchip_memory2_0_s1_byteenable -> onchip_memory2_0:byteenable
	wire         mm_interconnect_0_onchip_memory2_0_s1_write;                    // mm_interconnect_0:onchip_memory2_0_s1_write -> onchip_memory2_0:write
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_writedata;                // mm_interconnect_0:onchip_memory2_0_s1_writedata -> onchip_memory2_0:writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_clken;                    // mm_interconnect_0:onchip_memory2_0_s1_clken -> onchip_memory2_0:clken
	wire  [31:0] mm_interconnect_0_switches_s1_readdata;                         // switches:readdata -> mm_interconnect_0:switches_s1_readdata
	wire   [1:0] mm_interconnect_0_switches_s1_address;                          // mm_interconnect_0:switches_s1_address -> switches:address
	wire         mm_interconnect_0_leds_s1_chipselect;                           // mm_interconnect_0:LEDs_s1_chipselect -> LEDs:chipselect
	wire  [31:0] mm_interconnect_0_leds_s1_readdata;                             // LEDs:readdata -> mm_interconnect_0:LEDs_s1_readdata
	wire   [1:0] mm_interconnect_0_leds_s1_address;                              // mm_interconnect_0:LEDs_s1_address -> LEDs:address
	wire         mm_interconnect_0_leds_s1_write;                                // mm_interconnect_0:LEDs_s1_write -> LEDs:write_n
	wire  [31:0] mm_interconnect_0_leds_s1_writedata;                            // mm_interconnect_0:LEDs_s1_writedata -> LEDs:writedata
	wire         mm_interconnect_0_h0_s1_chipselect;                             // mm_interconnect_0:H0_s1_chipselect -> H0:chipselect
	wire  [31:0] mm_interconnect_0_h0_s1_readdata;                               // H0:readdata -> mm_interconnect_0:H0_s1_readdata
	wire   [1:0] mm_interconnect_0_h0_s1_address;                                // mm_interconnect_0:H0_s1_address -> H0:address
	wire         mm_interconnect_0_h0_s1_write;                                  // mm_interconnect_0:H0_s1_write -> H0:write_n
	wire  [31:0] mm_interconnect_0_h0_s1_writedata;                              // mm_interconnect_0:H0_s1_writedata -> H0:writedata
	wire         mm_interconnect_0_h1_s1_chipselect;                             // mm_interconnect_0:H1_s1_chipselect -> H1:chipselect
	wire  [31:0] mm_interconnect_0_h1_s1_readdata;                               // H1:readdata -> mm_interconnect_0:H1_s1_readdata
	wire   [1:0] mm_interconnect_0_h1_s1_address;                                // mm_interconnect_0:H1_s1_address -> H1:address
	wire         mm_interconnect_0_h1_s1_write;                                  // mm_interconnect_0:H1_s1_write -> H1:write_n
	wire  [31:0] mm_interconnect_0_h1_s1_writedata;                              // mm_interconnect_0:H1_s1_writedata -> H1:writedata
	wire         mm_interconnect_0_h2_s1_chipselect;                             // mm_interconnect_0:H2_s1_chipselect -> H2:chipselect
	wire  [31:0] mm_interconnect_0_h2_s1_readdata;                               // H2:readdata -> mm_interconnect_0:H2_s1_readdata
	wire   [1:0] mm_interconnect_0_h2_s1_address;                                // mm_interconnect_0:H2_s1_address -> H2:address
	wire         mm_interconnect_0_h2_s1_write;                                  // mm_interconnect_0:H2_s1_write -> H2:write_n
	wire  [31:0] mm_interconnect_0_h2_s1_writedata;                              // mm_interconnect_0:H2_s1_writedata -> H2:writedata
	wire         mm_interconnect_0_h3_s1_chipselect;                             // mm_interconnect_0:H3_s1_chipselect -> H3:chipselect
	wire  [31:0] mm_interconnect_0_h3_s1_readdata;                               // H3:readdata -> mm_interconnect_0:H3_s1_readdata
	wire   [1:0] mm_interconnect_0_h3_s1_address;                                // mm_interconnect_0:H3_s1_address -> H3:address
	wire         mm_interconnect_0_h3_s1_write;                                  // mm_interconnect_0:H3_s1_write -> H3:write_n
	wire  [31:0] mm_interconnect_0_h3_s1_writedata;                              // mm_interconnect_0:H3_s1_writedata -> H3:writedata
	wire         mm_interconnect_0_h4_s1_chipselect;                             // mm_interconnect_0:H4_s1_chipselect -> H4:chipselect
	wire  [31:0] mm_interconnect_0_h4_s1_readdata;                               // H4:readdata -> mm_interconnect_0:H4_s1_readdata
	wire   [1:0] mm_interconnect_0_h4_s1_address;                                // mm_interconnect_0:H4_s1_address -> H4:address
	wire         mm_interconnect_0_h4_s1_write;                                  // mm_interconnect_0:H4_s1_write -> H4:write_n
	wire  [31:0] mm_interconnect_0_h4_s1_writedata;                              // mm_interconnect_0:H4_s1_writedata -> H4:writedata
	wire         mm_interconnect_0_h5_s1_chipselect;                             // mm_interconnect_0:H5_s1_chipselect -> H5:chipselect
	wire  [31:0] mm_interconnect_0_h5_s1_readdata;                               // H5:readdata -> mm_interconnect_0:H5_s1_readdata
	wire   [1:0] mm_interconnect_0_h5_s1_address;                                // mm_interconnect_0:H5_s1_address -> H5:address
	wire         mm_interconnect_0_h5_s1_write;                                  // mm_interconnect_0:H5_s1_write -> H5:write_n
	wire  [31:0] mm_interconnect_0_h5_s1_writedata;                              // mm_interconnect_0:H5_s1_writedata -> H5:writedata
	wire         mm_interconnect_0_h6_s1_chipselect;                             // mm_interconnect_0:H6_s1_chipselect -> H6:chipselect
	wire  [31:0] mm_interconnect_0_h6_s1_readdata;                               // H6:readdata -> mm_interconnect_0:H6_s1_readdata
	wire   [1:0] mm_interconnect_0_h6_s1_address;                                // mm_interconnect_0:H6_s1_address -> H6:address
	wire         mm_interconnect_0_h6_s1_write;                                  // mm_interconnect_0:H6_s1_write -> H6:write_n
	wire  [31:0] mm_interconnect_0_h6_s1_writedata;                              // mm_interconnect_0:H6_s1_writedata -> H6:writedata
	wire         mm_interconnect_0_h7_s1_chipselect;                             // mm_interconnect_0:H7_s1_chipselect -> H7:chipselect
	wire  [31:0] mm_interconnect_0_h7_s1_readdata;                               // H7:readdata -> mm_interconnect_0:H7_s1_readdata
	wire   [1:0] mm_interconnect_0_h7_s1_address;                                // mm_interconnect_0:H7_s1_address -> H7:address
	wire         mm_interconnect_0_h7_s1_write;                                  // mm_interconnect_0:H7_s1_write -> H7:write_n
	wire  [31:0] mm_interconnect_0_h7_s1_writedata;                              // mm_interconnect_0:H7_s1_writedata -> H7:writedata
	wire         mm_interconnect_0_sdram_s1_chipselect;                          // mm_interconnect_0:sdram_s1_chipselect -> sdram:az_cs
	wire  [31:0] mm_interconnect_0_sdram_s1_readdata;                            // sdram:za_data -> mm_interconnect_0:sdram_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                         // sdram:za_waitrequest -> mm_interconnect_0:sdram_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                             // mm_interconnect_0:sdram_s1_address -> sdram:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                                // mm_interconnect_0:sdram_s1_read -> sdram:az_rd_n
	wire   [3:0] mm_interconnect_0_sdram_s1_byteenable;                          // mm_interconnect_0:sdram_s1_byteenable -> sdram:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                       // sdram:za_valid -> mm_interconnect_0:sdram_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                               // mm_interconnect_0:sdram_s1_write -> sdram:az_wr_n
	wire  [31:0] mm_interconnect_0_sdram_s1_writedata;                           // mm_interconnect_0:sdram_s1_writedata -> sdram:az_data
	wire         irq_mapper_receiver0_irq;                                       // jtag_uart_0:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios2_qsys_0_d_irq_irq;                                         // irq_mapper:sender_irq -> nios2_qsys_0:d_irq
	wire         rst_controller_reset_out_reset;                                 // rst_controller:reset_out -> [H0:reset_n, H1:reset_n, H2:reset_n, H3:reset_n, H4:reset_n, H5:reset_n, H6:reset_n, H7:reset_n, LEDs:reset_n, character_lcd_0:reset, irq_mapper:reset, jtag_uart_0:rst_n, mm_interconnect_0:nios2_qsys_0_reset_n_reset_bridge_in_reset_reset, nios2_qsys_0:reset_n, onchip_memory2_0:reset, rst_translator:in_reset, sdram:reset_n, switches:reset_n]
	wire         rst_controller_reset_out_reset_req;                             // rst_controller:reset_req -> [nios2_qsys_0:reset_req, onchip_memory2_0:reset_req, rst_translator:reset_req_in]
	wire         nios2_qsys_0_jtag_debug_module_reset_reset;                     // nios2_qsys_0:jtag_debug_module_resetrequest -> rst_controller:reset_in0
	wire         clocks_reset_source_reset;                                      // clocks:reset_source_reset -> rst_controller:reset_in1

	nios_system_H0 h0 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h0_s1_readdata),   //                    .readdata
		.out_port   (h0_export)                           // external_connection.export
	);

	nios_system_H0 h1 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h1_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h1_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h1_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h1_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h1_s1_readdata),   //                    .readdata
		.out_port   (h1_export)                           // external_connection.export
	);

	nios_system_H0 h2 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h2_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h2_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h2_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h2_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h2_s1_readdata),   //                    .readdata
		.out_port   (h2_export)                           // external_connection.export
	);

	nios_system_H0 h3 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h3_s1_readdata),   //                    .readdata
		.out_port   (h3_export)                           // external_connection.export
	);

	nios_system_H0 h4 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h4_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h4_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h4_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h4_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h4_s1_readdata),   //                    .readdata
		.out_port   (h4_export)                           // external_connection.export
	);

	nios_system_H0 h5 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h5_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h5_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h5_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h5_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h5_s1_readdata),   //                    .readdata
		.out_port   (h5_export)                           // external_connection.export
	);

	nios_system_H0 h6 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h6_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h6_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h6_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h6_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h6_s1_readdata),   //                    .readdata
		.out_port   (h6_export)                           // external_connection.export
	);

	nios_system_H0 h7 (
		.clk        (clocks_sys_clk_clk),                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_h7_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h7_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h7_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h7_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h7_s1_readdata),   //                    .readdata
		.out_port   (h7_export)                           // external_connection.export
	);

	nios_system_H0 leds (
		.clk        (clocks_sys_clk_clk),                   //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_leds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_leds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_leds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_leds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_leds_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                           // external_connection.export
	);

	nios_system_character_lcd_0 character_lcd_0 (
		.clk         (clocks_sys_clk_clk),                                             //                clk.clk
		.reset       (rst_controller_reset_out_reset),                                 //              reset.reset
		.address     (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_address),     //   avalon_lcd_slave.address
		.chipselect  (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_chipselect),  //                   .chipselect
		.read        (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_read),        //                   .read
		.write       (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_write),       //                   .write
		.writedata   (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_writedata),   //                   .writedata
		.readdata    (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_readdata),    //                   .readdata
		.waitrequest (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_waitrequest), //                   .waitrequest
		.LCD_DATA    (lcd_DATA),                                                       // external_interface.export
		.LCD_ON      (lcd_ON),                                                         //                   .export
		.LCD_BLON    (lcd_BLON),                                                       //                   .export
		.LCD_EN      (lcd_EN),                                                         //                   .export
		.LCD_RS      (lcd_RS),                                                         //                   .export
		.LCD_RW      (lcd_RW)                                                          //                   .export
	);

	nios_system_clocks clocks (
		.ref_clk_clk        (clk_clk),                   //      ref_clk.clk
		.ref_reset_reset    (reset_reset),               //    ref_reset.reset
		.sys_clk_clk        (clocks_sys_clk_clk),        //      sys_clk.clk
		.sdram_clk_clk      (sdram_clk_clk),             //    sdram_clk.clk
		.reset_source_reset (clocks_reset_source_reset)  // reset_source.reset
	);

	nios_system_jtag_uart_0 jtag_uart_0 (
		.clk            (clocks_sys_clk_clk),                                          //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                             //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                     //               irq.irq
	);

	nios_system_nios2_qsys_0 nios2_qsys_0 (
		.clk                                   (clocks_sys_clk_clk),                                           //                       clk.clk
		.reset_n                               (~rst_controller_reset_out_reset),                              //                   reset_n.reset_n
		.reset_req                             (rst_controller_reset_out_reset_req),                           //                          .reset_req
		.d_address                             (nios2_qsys_0_data_master_address),                             //               data_master.address
		.d_byteenable                          (nios2_qsys_0_data_master_byteenable),                          //                          .byteenable
		.d_read                                (nios2_qsys_0_data_master_read),                                //                          .read
		.d_readdata                            (nios2_qsys_0_data_master_readdata),                            //                          .readdata
		.d_waitrequest                         (nios2_qsys_0_data_master_waitrequest),                         //                          .waitrequest
		.d_write                               (nios2_qsys_0_data_master_write),                               //                          .write
		.d_writedata                           (nios2_qsys_0_data_master_writedata),                           //                          .writedata
		.d_readdatavalid                       (nios2_qsys_0_data_master_readdatavalid),                       //                          .readdatavalid
		.jtag_debug_module_debugaccess_to_roms (nios2_qsys_0_data_master_debugaccess),                         //                          .debugaccess
		.i_address                             (nios2_qsys_0_instruction_master_address),                      //        instruction_master.address
		.i_read                                (nios2_qsys_0_instruction_master_read),                         //                          .read
		.i_readdata                            (nios2_qsys_0_instruction_master_readdata),                     //                          .readdata
		.i_waitrequest                         (nios2_qsys_0_instruction_master_waitrequest),                  //                          .waitrequest
		.i_readdatavalid                       (nios2_qsys_0_instruction_master_readdatavalid),                //                          .readdatavalid
		.d_irq                                 (nios2_qsys_0_d_irq_irq),                                       //                     d_irq.irq
		.jtag_debug_module_resetrequest        (nios2_qsys_0_jtag_debug_module_reset_reset),                   //   jtag_debug_module_reset.reset
		.jtag_debug_module_address             (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_address),     //         jtag_debug_module.address
		.jtag_debug_module_byteenable          (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_byteenable),  //                          .byteenable
		.jtag_debug_module_debugaccess         (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_debugaccess), //                          .debugaccess
		.jtag_debug_module_read                (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_read),        //                          .read
		.jtag_debug_module_readdata            (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_readdata),    //                          .readdata
		.jtag_debug_module_waitrequest         (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_waitrequest), //                          .waitrequest
		.jtag_debug_module_write               (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_write),       //                          .write
		.jtag_debug_module_writedata           (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_writedata),   //                          .writedata
		.no_ci_readra                          ()                                                              // custom_instruction_master.readra
	);

	nios_system_onchip_memory2_0 onchip_memory2_0 (
		.clk        (clocks_sys_clk_clk),                               //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory2_0_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory2_0_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory2_0_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory2_0_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory2_0_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory2_0_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory2_0_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                   // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),               //       .reset_req
		.freeze     (1'b0)                                              // (terminated)
	);

	nios_system_sdram sdram (
		.clk            (clocks_sys_clk_clk),                       //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	nios_system_switches switches (
		.clk      (clocks_sys_clk_clk),                     //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_switches_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_switches_s1_readdata), //                    .readdata
		.in_port  (switches_export)                         // external_connection.export
	);

	nios_system_mm_interconnect_0 mm_interconnect_0 (
		.clocks_sys_clk_clk                               (clocks_sys_clk_clk),                                             //                             clocks_sys_clk.clk
		.nios2_qsys_0_reset_n_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                                 // nios2_qsys_0_reset_n_reset_bridge_in_reset.reset
		.nios2_qsys_0_data_master_address                 (nios2_qsys_0_data_master_address),                               //                   nios2_qsys_0_data_master.address
		.nios2_qsys_0_data_master_waitrequest             (nios2_qsys_0_data_master_waitrequest),                           //                                           .waitrequest
		.nios2_qsys_0_data_master_byteenable              (nios2_qsys_0_data_master_byteenable),                            //                                           .byteenable
		.nios2_qsys_0_data_master_read                    (nios2_qsys_0_data_master_read),                                  //                                           .read
		.nios2_qsys_0_data_master_readdata                (nios2_qsys_0_data_master_readdata),                              //                                           .readdata
		.nios2_qsys_0_data_master_readdatavalid           (nios2_qsys_0_data_master_readdatavalid),                         //                                           .readdatavalid
		.nios2_qsys_0_data_master_write                   (nios2_qsys_0_data_master_write),                                 //                                           .write
		.nios2_qsys_0_data_master_writedata               (nios2_qsys_0_data_master_writedata),                             //                                           .writedata
		.nios2_qsys_0_data_master_debugaccess             (nios2_qsys_0_data_master_debugaccess),                           //                                           .debugaccess
		.nios2_qsys_0_instruction_master_address          (nios2_qsys_0_instruction_master_address),                        //            nios2_qsys_0_instruction_master.address
		.nios2_qsys_0_instruction_master_waitrequest      (nios2_qsys_0_instruction_master_waitrequest),                    //                                           .waitrequest
		.nios2_qsys_0_instruction_master_read             (nios2_qsys_0_instruction_master_read),                           //                                           .read
		.nios2_qsys_0_instruction_master_readdata         (nios2_qsys_0_instruction_master_readdata),                       //                                           .readdata
		.nios2_qsys_0_instruction_master_readdatavalid    (nios2_qsys_0_instruction_master_readdatavalid),                  //                                           .readdatavalid
		.character_lcd_0_avalon_lcd_slave_address         (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_address),     //           character_lcd_0_avalon_lcd_slave.address
		.character_lcd_0_avalon_lcd_slave_write           (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_write),       //                                           .write
		.character_lcd_0_avalon_lcd_slave_read            (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_read),        //                                           .read
		.character_lcd_0_avalon_lcd_slave_readdata        (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_readdata),    //                                           .readdata
		.character_lcd_0_avalon_lcd_slave_writedata       (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_writedata),   //                                           .writedata
		.character_lcd_0_avalon_lcd_slave_waitrequest     (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_waitrequest), //                                           .waitrequest
		.character_lcd_0_avalon_lcd_slave_chipselect      (mm_interconnect_0_character_lcd_0_avalon_lcd_slave_chipselect),  //                                           .chipselect
		.H0_s1_address                                    (mm_interconnect_0_h0_s1_address),                                //                                      H0_s1.address
		.H0_s1_write                                      (mm_interconnect_0_h0_s1_write),                                  //                                           .write
		.H0_s1_readdata                                   (mm_interconnect_0_h0_s1_readdata),                               //                                           .readdata
		.H0_s1_writedata                                  (mm_interconnect_0_h0_s1_writedata),                              //                                           .writedata
		.H0_s1_chipselect                                 (mm_interconnect_0_h0_s1_chipselect),                             //                                           .chipselect
		.H1_s1_address                                    (mm_interconnect_0_h1_s1_address),                                //                                      H1_s1.address
		.H1_s1_write                                      (mm_interconnect_0_h1_s1_write),                                  //                                           .write
		.H1_s1_readdata                                   (mm_interconnect_0_h1_s1_readdata),                               //                                           .readdata
		.H1_s1_writedata                                  (mm_interconnect_0_h1_s1_writedata),                              //                                           .writedata
		.H1_s1_chipselect                                 (mm_interconnect_0_h1_s1_chipselect),                             //                                           .chipselect
		.H2_s1_address                                    (mm_interconnect_0_h2_s1_address),                                //                                      H2_s1.address
		.H2_s1_write                                      (mm_interconnect_0_h2_s1_write),                                  //                                           .write
		.H2_s1_readdata                                   (mm_interconnect_0_h2_s1_readdata),                               //                                           .readdata
		.H2_s1_writedata                                  (mm_interconnect_0_h2_s1_writedata),                              //                                           .writedata
		.H2_s1_chipselect                                 (mm_interconnect_0_h2_s1_chipselect),                             //                                           .chipselect
		.H3_s1_address                                    (mm_interconnect_0_h3_s1_address),                                //                                      H3_s1.address
		.H3_s1_write                                      (mm_interconnect_0_h3_s1_write),                                  //                                           .write
		.H3_s1_readdata                                   (mm_interconnect_0_h3_s1_readdata),                               //                                           .readdata
		.H3_s1_writedata                                  (mm_interconnect_0_h3_s1_writedata),                              //                                           .writedata
		.H3_s1_chipselect                                 (mm_interconnect_0_h3_s1_chipselect),                             //                                           .chipselect
		.H4_s1_address                                    (mm_interconnect_0_h4_s1_address),                                //                                      H4_s1.address
		.H4_s1_write                                      (mm_interconnect_0_h4_s1_write),                                  //                                           .write
		.H4_s1_readdata                                   (mm_interconnect_0_h4_s1_readdata),                               //                                           .readdata
		.H4_s1_writedata                                  (mm_interconnect_0_h4_s1_writedata),                              //                                           .writedata
		.H4_s1_chipselect                                 (mm_interconnect_0_h4_s1_chipselect),                             //                                           .chipselect
		.H5_s1_address                                    (mm_interconnect_0_h5_s1_address),                                //                                      H5_s1.address
		.H5_s1_write                                      (mm_interconnect_0_h5_s1_write),                                  //                                           .write
		.H5_s1_readdata                                   (mm_interconnect_0_h5_s1_readdata),                               //                                           .readdata
		.H5_s1_writedata                                  (mm_interconnect_0_h5_s1_writedata),                              //                                           .writedata
		.H5_s1_chipselect                                 (mm_interconnect_0_h5_s1_chipselect),                             //                                           .chipselect
		.H6_s1_address                                    (mm_interconnect_0_h6_s1_address),                                //                                      H6_s1.address
		.H6_s1_write                                      (mm_interconnect_0_h6_s1_write),                                  //                                           .write
		.H6_s1_readdata                                   (mm_interconnect_0_h6_s1_readdata),                               //                                           .readdata
		.H6_s1_writedata                                  (mm_interconnect_0_h6_s1_writedata),                              //                                           .writedata
		.H6_s1_chipselect                                 (mm_interconnect_0_h6_s1_chipselect),                             //                                           .chipselect
		.H7_s1_address                                    (mm_interconnect_0_h7_s1_address),                                //                                      H7_s1.address
		.H7_s1_write                                      (mm_interconnect_0_h7_s1_write),                                  //                                           .write
		.H7_s1_readdata                                   (mm_interconnect_0_h7_s1_readdata),                               //                                           .readdata
		.H7_s1_writedata                                  (mm_interconnect_0_h7_s1_writedata),                              //                                           .writedata
		.H7_s1_chipselect                                 (mm_interconnect_0_h7_s1_chipselect),                             //                                           .chipselect
		.jtag_uart_0_avalon_jtag_slave_address            (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),        //              jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write              (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),          //                                           .write
		.jtag_uart_0_avalon_jtag_slave_read               (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),           //                                           .read
		.jtag_uart_0_avalon_jtag_slave_readdata           (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),       //                                           .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata          (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),      //                                           .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest        (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest),    //                                           .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect         (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),     //                                           .chipselect
		.LEDs_s1_address                                  (mm_interconnect_0_leds_s1_address),                              //                                    LEDs_s1.address
		.LEDs_s1_write                                    (mm_interconnect_0_leds_s1_write),                                //                                           .write
		.LEDs_s1_readdata                                 (mm_interconnect_0_leds_s1_readdata),                             //                                           .readdata
		.LEDs_s1_writedata                                (mm_interconnect_0_leds_s1_writedata),                            //                                           .writedata
		.LEDs_s1_chipselect                               (mm_interconnect_0_leds_s1_chipselect),                           //                                           .chipselect
		.nios2_qsys_0_jtag_debug_module_address           (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_address),       //             nios2_qsys_0_jtag_debug_module.address
		.nios2_qsys_0_jtag_debug_module_write             (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_write),         //                                           .write
		.nios2_qsys_0_jtag_debug_module_read              (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_read),          //                                           .read
		.nios2_qsys_0_jtag_debug_module_readdata          (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_readdata),      //                                           .readdata
		.nios2_qsys_0_jtag_debug_module_writedata         (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_writedata),     //                                           .writedata
		.nios2_qsys_0_jtag_debug_module_byteenable        (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_byteenable),    //                                           .byteenable
		.nios2_qsys_0_jtag_debug_module_waitrequest       (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_waitrequest),   //                                           .waitrequest
		.nios2_qsys_0_jtag_debug_module_debugaccess       (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_debugaccess),   //                                           .debugaccess
		.onchip_memory2_0_s1_address                      (mm_interconnect_0_onchip_memory2_0_s1_address),                  //                        onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_write                        (mm_interconnect_0_onchip_memory2_0_s1_write),                    //                                           .write
		.onchip_memory2_0_s1_readdata                     (mm_interconnect_0_onchip_memory2_0_s1_readdata),                 //                                           .readdata
		.onchip_memory2_0_s1_writedata                    (mm_interconnect_0_onchip_memory2_0_s1_writedata),                //                                           .writedata
		.onchip_memory2_0_s1_byteenable                   (mm_interconnect_0_onchip_memory2_0_s1_byteenable),               //                                           .byteenable
		.onchip_memory2_0_s1_chipselect                   (mm_interconnect_0_onchip_memory2_0_s1_chipselect),               //                                           .chipselect
		.onchip_memory2_0_s1_clken                        (mm_interconnect_0_onchip_memory2_0_s1_clken),                    //                                           .clken
		.sdram_s1_address                                 (mm_interconnect_0_sdram_s1_address),                             //                                   sdram_s1.address
		.sdram_s1_write                                   (mm_interconnect_0_sdram_s1_write),                               //                                           .write
		.sdram_s1_read                                    (mm_interconnect_0_sdram_s1_read),                                //                                           .read
		.sdram_s1_readdata                                (mm_interconnect_0_sdram_s1_readdata),                            //                                           .readdata
		.sdram_s1_writedata                               (mm_interconnect_0_sdram_s1_writedata),                           //                                           .writedata
		.sdram_s1_byteenable                              (mm_interconnect_0_sdram_s1_byteenable),                          //                                           .byteenable
		.sdram_s1_readdatavalid                           (mm_interconnect_0_sdram_s1_readdatavalid),                       //                                           .readdatavalid
		.sdram_s1_waitrequest                             (mm_interconnect_0_sdram_s1_waitrequest),                         //                                           .waitrequest
		.sdram_s1_chipselect                              (mm_interconnect_0_sdram_s1_chipselect),                          //                                           .chipselect
		.switches_s1_address                              (mm_interconnect_0_switches_s1_address),                          //                                switches_s1.address
		.switches_s1_readdata                             (mm_interconnect_0_switches_s1_readdata)                          //                                           .readdata
	);

	nios_system_irq_mapper irq_mapper (
		.clk           (clocks_sys_clk_clk),             //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios2_qsys_0_d_irq_irq)          //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (nios2_qsys_0_jtag_debug_module_reset_reset), // reset_in0.reset
		.reset_in1      (clocks_reset_source_reset),                  // reset_in1.reset
		.clk            (clocks_sys_clk_clk),                         //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),             // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),         //          .reset_req
		.reset_req_in0  (1'b0),                                       // (terminated)
		.reset_req_in1  (1'b0),                                       // (terminated)
		.reset_in2      (1'b0),                                       // (terminated)
		.reset_req_in2  (1'b0),                                       // (terminated)
		.reset_in3      (1'b0),                                       // (terminated)
		.reset_req_in3  (1'b0),                                       // (terminated)
		.reset_in4      (1'b0),                                       // (terminated)
		.reset_req_in4  (1'b0),                                       // (terminated)
		.reset_in5      (1'b0),                                       // (terminated)
		.reset_req_in5  (1'b0),                                       // (terminated)
		.reset_in6      (1'b0),                                       // (terminated)
		.reset_req_in6  (1'b0),                                       // (terminated)
		.reset_in7      (1'b0),                                       // (terminated)
		.reset_req_in7  (1'b0),                                       // (terminated)
		.reset_in8      (1'b0),                                       // (terminated)
		.reset_req_in8  (1'b0),                                       // (terminated)
		.reset_in9      (1'b0),                                       // (terminated)
		.reset_req_in9  (1'b0),                                       // (terminated)
		.reset_in10     (1'b0),                                       // (terminated)
		.reset_req_in10 (1'b0),                                       // (terminated)
		.reset_in11     (1'b0),                                       // (terminated)
		.reset_req_in11 (1'b0),                                       // (terminated)
		.reset_in12     (1'b0),                                       // (terminated)
		.reset_req_in12 (1'b0),                                       // (terminated)
		.reset_in13     (1'b0),                                       // (terminated)
		.reset_req_in13 (1'b0),                                       // (terminated)
		.reset_in14     (1'b0),                                       // (terminated)
		.reset_req_in14 (1'b0),                                       // (terminated)
		.reset_in15     (1'b0),                                       // (terminated)
		.reset_req_in15 (1'b0)                                        // (terminated)
	);

endmodule
